/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef EngineService_H
#define EngineService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "engine_types.h"

namespace engine {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class EngineServiceIf {
 public:
  virtual ~EngineServiceIf() {}
  virtual void Hello(HelloReply& _return, const HelloRequest& req) = 0;
  virtual void EstimatePi(PiReply& _return, const PiRequest& req) = 0;
  virtual void MatMul(MatReply& _return, const MatMulRequest& req) = 0;
  virtual void ComputeStats(VectorStatsReply& _return, const VectorStatsRequest& req) = 0;
};

class EngineServiceIfFactory {
 public:
  typedef EngineServiceIf Handler;

  virtual ~EngineServiceIfFactory() {}

  virtual EngineServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(EngineServiceIf* /* handler */) = 0;
  };

class EngineServiceIfSingletonFactory : virtual public EngineServiceIfFactory {
 public:
  EngineServiceIfSingletonFactory(const ::std::shared_ptr<EngineServiceIf>& iface) : iface_(iface) {}
  virtual ~EngineServiceIfSingletonFactory() {}

  virtual EngineServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(EngineServiceIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<EngineServiceIf> iface_;
};

class EngineServiceNull : virtual public EngineServiceIf {
 public:
  virtual ~EngineServiceNull() {}
  void Hello(HelloReply& /* _return */, const HelloRequest& /* req */) override {
    return;
  }
  void EstimatePi(PiReply& /* _return */, const PiRequest& /* req */) override {
    return;
  }
  void MatMul(MatReply& /* _return */, const MatMulRequest& /* req */) override {
    return;
  }
  void ComputeStats(VectorStatsReply& /* _return */, const VectorStatsRequest& /* req */) override {
    return;
  }
};

typedef struct _EngineService_Hello_args__isset {
  _EngineService_Hello_args__isset() : req(false) {}
  bool req :1;
} _EngineService_Hello_args__isset;

class EngineService_Hello_args {
 public:

  EngineService_Hello_args(const EngineService_Hello_args&);
  EngineService_Hello_args& operator=(const EngineService_Hello_args&);
  EngineService_Hello_args() noexcept {
  }

  virtual ~EngineService_Hello_args() noexcept;
  HelloRequest req;

  _EngineService_Hello_args__isset __isset;

  void __set_req(const HelloRequest& val);

  bool operator == (const EngineService_Hello_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const EngineService_Hello_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EngineService_Hello_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineService_Hello_pargs {
 public:


  virtual ~EngineService_Hello_pargs() noexcept;
  const HelloRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineService_Hello_result__isset {
  _EngineService_Hello_result__isset() : success(false) {}
  bool success :1;
} _EngineService_Hello_result__isset;

class EngineService_Hello_result {
 public:

  EngineService_Hello_result(const EngineService_Hello_result&);
  EngineService_Hello_result& operator=(const EngineService_Hello_result&);
  EngineService_Hello_result() noexcept {
  }

  virtual ~EngineService_Hello_result() noexcept;
  HelloReply success;

  _EngineService_Hello_result__isset __isset;

  void __set_success(const HelloReply& val);

  bool operator == (const EngineService_Hello_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const EngineService_Hello_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EngineService_Hello_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineService_Hello_presult__isset {
  _EngineService_Hello_presult__isset() : success(false) {}
  bool success :1;
} _EngineService_Hello_presult__isset;

class EngineService_Hello_presult {
 public:


  virtual ~EngineService_Hello_presult() noexcept;
  HelloReply* success;

  _EngineService_Hello_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineService_EstimatePi_args__isset {
  _EngineService_EstimatePi_args__isset() : req(false) {}
  bool req :1;
} _EngineService_EstimatePi_args__isset;

class EngineService_EstimatePi_args {
 public:

  EngineService_EstimatePi_args(const EngineService_EstimatePi_args&) noexcept;
  EngineService_EstimatePi_args& operator=(const EngineService_EstimatePi_args&) noexcept;
  EngineService_EstimatePi_args() noexcept {
  }

  virtual ~EngineService_EstimatePi_args() noexcept;
  PiRequest req;

  _EngineService_EstimatePi_args__isset __isset;

  void __set_req(const PiRequest& val);

  bool operator == (const EngineService_EstimatePi_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const EngineService_EstimatePi_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EngineService_EstimatePi_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineService_EstimatePi_pargs {
 public:


  virtual ~EngineService_EstimatePi_pargs() noexcept;
  const PiRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineService_EstimatePi_result__isset {
  _EngineService_EstimatePi_result__isset() : success(false) {}
  bool success :1;
} _EngineService_EstimatePi_result__isset;

class EngineService_EstimatePi_result {
 public:

  EngineService_EstimatePi_result(const EngineService_EstimatePi_result&) noexcept;
  EngineService_EstimatePi_result& operator=(const EngineService_EstimatePi_result&) noexcept;
  EngineService_EstimatePi_result() noexcept {
  }

  virtual ~EngineService_EstimatePi_result() noexcept;
  PiReply success;

  _EngineService_EstimatePi_result__isset __isset;

  void __set_success(const PiReply& val);

  bool operator == (const EngineService_EstimatePi_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const EngineService_EstimatePi_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EngineService_EstimatePi_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineService_EstimatePi_presult__isset {
  _EngineService_EstimatePi_presult__isset() : success(false) {}
  bool success :1;
} _EngineService_EstimatePi_presult__isset;

class EngineService_EstimatePi_presult {
 public:


  virtual ~EngineService_EstimatePi_presult() noexcept;
  PiReply* success;

  _EngineService_EstimatePi_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineService_MatMul_args__isset {
  _EngineService_MatMul_args__isset() : req(false) {}
  bool req :1;
} _EngineService_MatMul_args__isset;

class EngineService_MatMul_args {
 public:

  EngineService_MatMul_args(const EngineService_MatMul_args&);
  EngineService_MatMul_args& operator=(const EngineService_MatMul_args&);
  EngineService_MatMul_args() noexcept {
  }

  virtual ~EngineService_MatMul_args() noexcept;
  MatMulRequest req;

  _EngineService_MatMul_args__isset __isset;

  void __set_req(const MatMulRequest& val);

  bool operator == (const EngineService_MatMul_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const EngineService_MatMul_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EngineService_MatMul_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineService_MatMul_pargs {
 public:


  virtual ~EngineService_MatMul_pargs() noexcept;
  const MatMulRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineService_MatMul_result__isset {
  _EngineService_MatMul_result__isset() : success(false) {}
  bool success :1;
} _EngineService_MatMul_result__isset;

class EngineService_MatMul_result {
 public:

  EngineService_MatMul_result(const EngineService_MatMul_result&);
  EngineService_MatMul_result& operator=(const EngineService_MatMul_result&);
  EngineService_MatMul_result() noexcept {
  }

  virtual ~EngineService_MatMul_result() noexcept;
  MatReply success;

  _EngineService_MatMul_result__isset __isset;

  void __set_success(const MatReply& val);

  bool operator == (const EngineService_MatMul_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const EngineService_MatMul_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EngineService_MatMul_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineService_MatMul_presult__isset {
  _EngineService_MatMul_presult__isset() : success(false) {}
  bool success :1;
} _EngineService_MatMul_presult__isset;

class EngineService_MatMul_presult {
 public:


  virtual ~EngineService_MatMul_presult() noexcept;
  MatReply* success;

  _EngineService_MatMul_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _EngineService_ComputeStats_args__isset {
  _EngineService_ComputeStats_args__isset() : req(false) {}
  bool req :1;
} _EngineService_ComputeStats_args__isset;

class EngineService_ComputeStats_args {
 public:

  EngineService_ComputeStats_args(const EngineService_ComputeStats_args&);
  EngineService_ComputeStats_args& operator=(const EngineService_ComputeStats_args&);
  EngineService_ComputeStats_args() noexcept {
  }

  virtual ~EngineService_ComputeStats_args() noexcept;
  VectorStatsRequest req;

  _EngineService_ComputeStats_args__isset __isset;

  void __set_req(const VectorStatsRequest& val);

  bool operator == (const EngineService_ComputeStats_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const EngineService_ComputeStats_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EngineService_ComputeStats_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class EngineService_ComputeStats_pargs {
 public:


  virtual ~EngineService_ComputeStats_pargs() noexcept;
  const VectorStatsRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineService_ComputeStats_result__isset {
  _EngineService_ComputeStats_result__isset() : success(false) {}
  bool success :1;
} _EngineService_ComputeStats_result__isset;

class EngineService_ComputeStats_result {
 public:

  EngineService_ComputeStats_result(const EngineService_ComputeStats_result&) noexcept;
  EngineService_ComputeStats_result& operator=(const EngineService_ComputeStats_result&) noexcept;
  EngineService_ComputeStats_result() noexcept {
  }

  virtual ~EngineService_ComputeStats_result() noexcept;
  VectorStatsReply success;

  _EngineService_ComputeStats_result__isset __isset;

  void __set_success(const VectorStatsReply& val);

  bool operator == (const EngineService_ComputeStats_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const EngineService_ComputeStats_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const EngineService_ComputeStats_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _EngineService_ComputeStats_presult__isset {
  _EngineService_ComputeStats_presult__isset() : success(false) {}
  bool success :1;
} _EngineService_ComputeStats_presult__isset;

class EngineService_ComputeStats_presult {
 public:


  virtual ~EngineService_ComputeStats_presult() noexcept;
  VectorStatsReply* success;

  _EngineService_ComputeStats_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class EngineServiceClient : virtual public EngineServiceIf {
 public:
  EngineServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  EngineServiceClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Hello(HelloReply& _return, const HelloRequest& req) override;
  void send_Hello(const HelloRequest& req);
  void recv_Hello(HelloReply& _return);
  void EstimatePi(PiReply& _return, const PiRequest& req) override;
  void send_EstimatePi(const PiRequest& req);
  void recv_EstimatePi(PiReply& _return);
  void MatMul(MatReply& _return, const MatMulRequest& req) override;
  void send_MatMul(const MatMulRequest& req);
  void recv_MatMul(MatReply& _return);
  void ComputeStats(VectorStatsReply& _return, const VectorStatsRequest& req) override;
  void send_ComputeStats(const VectorStatsRequest& req);
  void recv_ComputeStats(VectorStatsReply& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class EngineServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<EngineServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (EngineServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_Hello(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_EstimatePi(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_MatMul(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ComputeStats(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  EngineServiceProcessor(::std::shared_ptr<EngineServiceIf> iface) :
    iface_(iface) {
    processMap_["Hello"] = &EngineServiceProcessor::process_Hello;
    processMap_["EstimatePi"] = &EngineServiceProcessor::process_EstimatePi;
    processMap_["MatMul"] = &EngineServiceProcessor::process_MatMul;
    processMap_["ComputeStats"] = &EngineServiceProcessor::process_ComputeStats;
  }

  virtual ~EngineServiceProcessor() {}
};

class EngineServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  EngineServiceProcessorFactory(const ::std::shared_ptr< EngineServiceIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< EngineServiceIfFactory > handlerFactory_;
};

class EngineServiceMultiface : virtual public EngineServiceIf {
 public:
  EngineServiceMultiface(std::vector<std::shared_ptr<EngineServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~EngineServiceMultiface() {}
 protected:
  std::vector<std::shared_ptr<EngineServiceIf> > ifaces_;
  EngineServiceMultiface() {}
  void add(::std::shared_ptr<EngineServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void Hello(HelloReply& _return, const HelloRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->Hello(_return, req);
    }
    ifaces_[i]->Hello(_return, req);
    return;
  }

  void EstimatePi(PiReply& _return, const PiRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->EstimatePi(_return, req);
    }
    ifaces_[i]->EstimatePi(_return, req);
    return;
  }

  void MatMul(MatReply& _return, const MatMulRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->MatMul(_return, req);
    }
    ifaces_[i]->MatMul(_return, req);
    return;
  }

  void ComputeStats(VectorStatsReply& _return, const VectorStatsRequest& req) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ComputeStats(_return, req);
    }
    ifaces_[i]->ComputeStats(_return, req);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class EngineServiceConcurrentClient : virtual public EngineServiceIf {
 public:
  EngineServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  EngineServiceConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void Hello(HelloReply& _return, const HelloRequest& req) override;
  int32_t send_Hello(const HelloRequest& req);
  void recv_Hello(HelloReply& _return, const int32_t seqid);
  void EstimatePi(PiReply& _return, const PiRequest& req) override;
  int32_t send_EstimatePi(const PiRequest& req);
  void recv_EstimatePi(PiReply& _return, const int32_t seqid);
  void MatMul(MatReply& _return, const MatMulRequest& req) override;
  int32_t send_MatMul(const MatMulRequest& req);
  void recv_MatMul(MatReply& _return, const int32_t seqid);
  void ComputeStats(VectorStatsReply& _return, const VectorStatsRequest& req) override;
  int32_t send_ComputeStats(const VectorStatsRequest& req);
  void recv_ComputeStats(VectorStatsReply& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
