// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "EngineService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::engine;

class EngineServiceHandler : virtual public EngineServiceIf {
 public:
  EngineServiceHandler() {
    // Your initialization goes here
  }

  void Hello(HelloReply& _return, const HelloRequest& req) {
    // Your implementation goes here
    printf("Hello\n");
  }

  void EstimatePi(PiReply& _return, const PiRequest& req) {
    // Your implementation goes here
    printf("EstimatePi\n");
  }

  void MatMul(MatReply& _return, const MatMulRequest& req) {
    // Your implementation goes here
    printf("MatMul\n");
  }

  void ComputeStats(VectorStatsReply& _return, const VectorStatsRequest& req) {
    // Your implementation goes here
    printf("ComputeStats\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<EngineServiceHandler> handler(new EngineServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new EngineServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

