/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef engine_TYPES_H
#define engine_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace engine {

class HelloRequest;

class HelloReply;

class PiRequest;

class PiReply;

class Matrix;

class MatMulRequest;

class MatReply;

class VectorStatsRequest;

class VectorStatsReply;

typedef struct _HelloRequest__isset {
  _HelloRequest__isset() : name(false) {}
  bool name :1;
} _HelloRequest__isset;

class HelloRequest : public virtual ::apache::thrift::TBase {
 public:

  HelloRequest(const HelloRequest&);
  HelloRequest& operator=(const HelloRequest&);
  HelloRequest() noexcept
               : name() {
  }

  virtual ~HelloRequest() noexcept;
  std::string name;

  _HelloRequest__isset __isset;

  void __set_name(const std::string& val);

  bool operator == (const HelloRequest & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    return true;
  }
  bool operator != (const HelloRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(HelloRequest &a, HelloRequest &b);

std::ostream& operator<<(std::ostream& out, const HelloRequest& obj);

typedef struct _HelloReply__isset {
  _HelloReply__isset() : message(false) {}
  bool message :1;
} _HelloReply__isset;

class HelloReply : public virtual ::apache::thrift::TBase {
 public:

  HelloReply(const HelloReply&);
  HelloReply& operator=(const HelloReply&);
  HelloReply() noexcept
             : message() {
  }

  virtual ~HelloReply() noexcept;
  std::string message;

  _HelloReply__isset __isset;

  void __set_message(const std::string& val);

  bool operator == (const HelloReply & rhs) const
  {
    if (!(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const HelloReply &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloReply & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(HelloReply &a, HelloReply &b);

std::ostream& operator<<(std::ostream& out, const HelloReply& obj);

typedef struct _PiRequest__isset {
  _PiRequest__isset() : samples(false) {}
  bool samples :1;
} _PiRequest__isset;

class PiRequest : public virtual ::apache::thrift::TBase {
 public:

  PiRequest(const PiRequest&) noexcept;
  PiRequest& operator=(const PiRequest&) noexcept;
  PiRequest() noexcept
            : samples(0) {
  }

  virtual ~PiRequest() noexcept;
  int64_t samples;

  _PiRequest__isset __isset;

  void __set_samples(const int64_t val);

  bool operator == (const PiRequest & rhs) const
  {
    if (!(samples == rhs.samples))
      return false;
    return true;
  }
  bool operator != (const PiRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PiRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(PiRequest &a, PiRequest &b);

std::ostream& operator<<(std::ostream& out, const PiRequest& obj);

typedef struct _PiReply__isset {
  _PiReply__isset() : pi(false), inside(false), total(false), seed(false) {}
  bool pi :1;
  bool inside :1;
  bool total :1;
  bool seed :1;
} _PiReply__isset;

class PiReply : public virtual ::apache::thrift::TBase {
 public:

  PiReply(const PiReply&) noexcept;
  PiReply& operator=(const PiReply&) noexcept;
  PiReply() noexcept
          : pi(0),
            inside(0),
            total(0),
            seed(0) {
  }

  virtual ~PiReply() noexcept;
  double pi;
  int64_t inside;
  int64_t total;
  int64_t seed;

  _PiReply__isset __isset;

  void __set_pi(const double val);

  void __set_inside(const int64_t val);

  void __set_total(const int64_t val);

  void __set_seed(const int64_t val);

  bool operator == (const PiReply & rhs) const
  {
    if (!(pi == rhs.pi))
      return false;
    if (!(inside == rhs.inside))
      return false;
    if (!(total == rhs.total))
      return false;
    if (!(seed == rhs.seed))
      return false;
    return true;
  }
  bool operator != (const PiReply &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PiReply & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(PiReply &a, PiReply &b);

std::ostream& operator<<(std::ostream& out, const PiReply& obj);

typedef struct _Matrix__isset {
  _Matrix__isset() : rows(false), cols(false), data(false) {}
  bool rows :1;
  bool cols :1;
  bool data :1;
} _Matrix__isset;

class Matrix : public virtual ::apache::thrift::TBase {
 public:

  Matrix(const Matrix&);
  Matrix& operator=(const Matrix&);
  Matrix() noexcept
         : rows(0),
           cols(0) {
  }

  virtual ~Matrix() noexcept;
  int32_t rows;
  int32_t cols;
  std::vector<double>  data;

  _Matrix__isset __isset;

  void __set_rows(const int32_t val);

  void __set_cols(const int32_t val);

  void __set_data(const std::vector<double> & val);

  bool operator == (const Matrix & rhs) const
  {
    if (!(rows == rhs.rows))
      return false;
    if (!(cols == rhs.cols))
      return false;
    if (!(data == rhs.data))
      return false;
    return true;
  }
  bool operator != (const Matrix &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Matrix & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(Matrix &a, Matrix &b);

std::ostream& operator<<(std::ostream& out, const Matrix& obj);

typedef struct _MatMulRequest__isset {
  _MatMulRequest__isset() : a(false), b(false) {}
  bool a :1;
  bool b :1;
} _MatMulRequest__isset;

class MatMulRequest : public virtual ::apache::thrift::TBase {
 public:

  MatMulRequest(const MatMulRequest&);
  MatMulRequest& operator=(const MatMulRequest&);
  MatMulRequest() noexcept {
  }

  virtual ~MatMulRequest() noexcept;
  Matrix a;
  Matrix b;

  _MatMulRequest__isset __isset;

  void __set_a(const Matrix& val);

  void __set_b(const Matrix& val);

  bool operator == (const MatMulRequest & rhs) const
  {
    if (!(a == rhs.a))
      return false;
    if (!(b == rhs.b))
      return false;
    return true;
  }
  bool operator != (const MatMulRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MatMulRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(MatMulRequest &a, MatMulRequest &b);

std::ostream& operator<<(std::ostream& out, const MatMulRequest& obj);

typedef struct _MatReply__isset {
  _MatReply__isset() : c(false) {}
  bool c :1;
} _MatReply__isset;

class MatReply : public virtual ::apache::thrift::TBase {
 public:

  MatReply(const MatReply&);
  MatReply& operator=(const MatReply&);
  MatReply() noexcept {
  }

  virtual ~MatReply() noexcept;
  Matrix c;

  _MatReply__isset __isset;

  void __set_c(const Matrix& val);

  bool operator == (const MatReply & rhs) const
  {
    if (!(c == rhs.c))
      return false;
    return true;
  }
  bool operator != (const MatReply &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MatReply & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(MatReply &a, MatReply &b);

std::ostream& operator<<(std::ostream& out, const MatReply& obj);

typedef struct _VectorStatsRequest__isset {
  _VectorStatsRequest__isset() : data(false), sample(true) {}
  bool data :1;
  bool sample :1;
} _VectorStatsRequest__isset;

class VectorStatsRequest : public virtual ::apache::thrift::TBase {
 public:

  VectorStatsRequest(const VectorStatsRequest&);
  VectorStatsRequest& operator=(const VectorStatsRequest&);
  VectorStatsRequest() noexcept
                     : sample(true) {
  }

  virtual ~VectorStatsRequest() noexcept;
  std::vector<double>  data;
  bool sample;

  _VectorStatsRequest__isset __isset;

  void __set_data(const std::vector<double> & val);

  void __set_sample(const bool val);

  bool operator == (const VectorStatsRequest & rhs) const
  {
    if (!(data == rhs.data))
      return false;
    if (!(sample == rhs.sample))
      return false;
    return true;
  }
  bool operator != (const VectorStatsRequest &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VectorStatsRequest & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(VectorStatsRequest &a, VectorStatsRequest &b);

std::ostream& operator<<(std::ostream& out, const VectorStatsRequest& obj);

typedef struct _VectorStatsReply__isset {
  _VectorStatsReply__isset() : count(false), sum(false), mean(false), variance(false), stddev(false), min(false), max(false) {}
  bool count :1;
  bool sum :1;
  bool mean :1;
  bool variance :1;
  bool stddev :1;
  bool min :1;
  bool max :1;
} _VectorStatsReply__isset;

class VectorStatsReply : public virtual ::apache::thrift::TBase {
 public:

  VectorStatsReply(const VectorStatsReply&) noexcept;
  VectorStatsReply& operator=(const VectorStatsReply&) noexcept;
  VectorStatsReply() noexcept
                   : count(0),
                     sum(0),
                     mean(0),
                     variance(0),
                     stddev(0),
                     min(0),
                     max(0) {
  }

  virtual ~VectorStatsReply() noexcept;
  int64_t count;
  double sum;
  double mean;
  double variance;
  double stddev;
  double min;
  double max;

  _VectorStatsReply__isset __isset;

  void __set_count(const int64_t val);

  void __set_sum(const double val);

  void __set_mean(const double val);

  void __set_variance(const double val);

  void __set_stddev(const double val);

  void __set_min(const double val);

  void __set_max(const double val);

  bool operator == (const VectorStatsReply & rhs) const
  {
    if (!(count == rhs.count))
      return false;
    if (!(sum == rhs.sum))
      return false;
    if (!(mean == rhs.mean))
      return false;
    if (!(variance == rhs.variance))
      return false;
    if (!(stddev == rhs.stddev))
      return false;
    if (!(min == rhs.min))
      return false;
    if (!(max == rhs.max))
      return false;
    return true;
  }
  bool operator != (const VectorStatsReply &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const VectorStatsReply & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot) override;
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const override;

  virtual void printTo(std::ostream& out) const;
};

void swap(VectorStatsReply &a, VectorStatsReply &b);

std::ostream& operator<<(std::ostream& out, const VectorStatsReply& obj);

} // namespace

#endif
