root = "."
tmp_dir = "tmp"

[build]
# Build the new entry point
cmd = "go build -o ./tmp/api-gw ./cmd/api"
bin = "tmp/api-gw"
full_bin = "./tmp/api-gw"

# Watch all .go files but ignore build/tmp/vendor/gen folders
include_ext = ["go"]
exclude_dir = ["tmp", "vendor", "gen"]
