FROM ubuntu:22.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential cmake libthrift-dev libboost-all-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app/engine-cpp

COPY . /app/engine-cpp

# Build
RUN rm -rf build && mkdir build && cd build && cmake .. && make -j"$(nproc)"

EXPOSE 9101
CMD ["./build/engine"]
